[input]
url = "opc.tcp://opcua.demo-this.com:51210/UA/SampleServer"
	
[output]
name             = "influx_1"
type             = "influxdb"
host             = "188.166.17.134"
port             = 8086
protocol         = "http"
username         = ""
password         = ""
database         = "test"
failoverTimeout  = 10000
buffer_max_size  = 64
write_interval   = 1000
write_max_points = 1000

[[measurements]]
name               = "valve_position"
tags               = { equipment = "sterilisor 3", valve = "AB43" }
nodeId             = "ns=2;i=10849"
collectionType     = "polled"
pollRate           = 20     # samples / minute.
monitorResolution  = 100    # ms 
deadbandAbsolute   = 32     # Absolute max difference for a value not to be collected
deadbandRelative   = 0.0    # Relative max difference for a value not to be collected

[[measurements]]
name               = "valve_position"
tags               = { equipment = "sterilisor 1", valve = "AC43" }
nodeId             = "ns=2;i=10849"
collectionType     = "polled"
pollRate           = 10     # samples / minute.
monitorResolution  = 500    # ms 
deadbandAbsolute   = 32     # Absolute max difference for a value not to be collected
deadbandRelative   = 0.0    # Relative max difference for a value not to be collected